
export const CHOOSE_LANGUAGE = 'CHOOSE_LANGUAGE';
export const LEXER_ADD = 'LEXER_ADD';
export const LEXER_EDIT = 'LEXER_EDIT';
export const LEXER_DELETE = 'LEXER_DELETE';
export const LEXER_MODAL_DELETE_SHOW = 'LEXER_MODAL_DELETE_SHOW';
export const LEXER_MODAL_DELETE_HIDE = 'LEXER_MODAL_DELETE_HIDE';

export const CHOOSE_COURSE = 'CHOOSE_COURSE';
