
export const CHOOSE_LANGUAGE = 'CHOOSE_LANGUAGE';
export const LEXER_MODAL_DELETE_SHOW = 'LEXER_MODAL_DELETE_SHOW';
export const LEXER_MODAL_DELETE_HIDE = 'LEXER_MODAL_DELETE_HIDE';

export const CHOOSE_COURSE = 'CHOOSE_COURSE';

export const LEXER_FUNCTIONS_ID = 1;
export const LEXER_CATEGORY_ID = 3;
